In [1]:
import torch
import torch.nn as nn
import numpy as np
import random

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [5]:
# create a tensor that retains properties from other tensor
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [7]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.0316, 0.4962],
        [0.6175, 0.1035]])

In [9]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.0055, 0.1190, 0.8052],
        [0.9842, 0.4815, 0.2087]])

In [10]:
ones_tensor = torch.ones(shape)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# describing attributes
tensor = torch.rand(3, 4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)
tensor

torch.Size([3, 4])
torch.float32
cpu


tensor([[0.0145, 0.2228, 0.0935, 0.5116],
        [0.8968, 0.8928, 0.9435, 0.8685],
        [0.6227, 0.0427, 0.2397, 0.0919]])

In [14]:
# joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[0.0145, 0.2228, 0.0935, 0.5116, 0.0145, 0.2228, 0.0935, 0.5116, 0.0145,
         0.2228, 0.0935, 0.5116],
        [0.8968, 0.8928, 0.9435, 0.8685, 0.8968, 0.8928, 0.9435, 0.8685, 0.8968,
         0.8928, 0.9435, 0.8685],
        [0.6227, 0.0427, 0.2397, 0.0919, 0.6227, 0.0427, 0.2397, 0.0919, 0.6227,
         0.0427, 0.2397, 0.0919]])

In [29]:
tensor_zeros = torch.zeros(10, dtype=torch.float)
tensor_zeros.scatter(dim=0, index=torch.tensor([1]), value=1)

tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
from torchvision.transforms import ToTensor, Lambda

# one hot encode 10 labels
target_transform = Lambda(lambda y: torch.zeros(10, dtype=torch.float).scatter_(dim=0, index=torch.tensor(y), value=1))

In [32]:
target_transform(5)

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])